name: Infracost Comment

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  infracost:
    runs-on: ubuntu-latest
    env:
      working-directory: ec2/
      INFRACOST_GITHUB_ACTION: true
      INFRACOST_SKIP_UPDATE_CHECK: true
      INFRACOST_LOG_LEVEL: info

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ${{ env.working-directory }}

      - name: Terraform Plan
        run: terraform plan -out tfplan.binary
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ${{ env.working-directory }}

      - name: Terraform Show
        run: terraform show -json tfplan.binary > plan.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ${{ env.working-directory }}

      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost JSON
        run: infracost breakdown --path plan.json --format json --out-file /tmp/infracost.json
        working-directory: ${{ env.working-directory }}

      - name: Post Infracost comment
        run: |
          infracost comment github --path /tmp/infracost.json \
                                   --repo "${{ github.repository }}" \
                                   --commit "${{ github.sha }}" \
                                   --github-token "${{ secrets.GITHUB_TOKEN }}" \
                                   --behavior update



